# Generated by Django 3.0.1 on 2019-12-26 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userseeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy', models.CharField(default='None', max_length=100)),
                ('username', models.CharField(default='None', max_length=100)),
                ('password', models.CharField(default='None', max_length=100)),
                ('recoverymail', models.CharField(default='None', max_length=100)),
                ('user', models.CharField(max_length=100)),
            ],
        ),
    ]
