# Generated by Django 3.0.1 on 2020-01-01 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_machineconfig'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MachineConfig',
            new_name='MachineConfiguration',
        ),
        migrations.RenameModel(
            old_name='Userseeds',
            new_name='UserSeed',
        ),
    ]
