# Generated by Django 3.0.1 on 2020-01-10 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_auto_20200101_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineconfiguration',
            name='cpu_usage',
            field=models.CharField(default='Not Active', max_length=10),
        ),
        migrations.AddField(
            model_name='machineconfiguration',
            name='ram_usage',
            field=models.CharField(default='Not Active', max_length=10),
        ),
    ]
