# Generated by Django 3.0.1 on 2020-01-10 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_auto_20200110_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineconfiguration',
            name='user',
            field=models.CharField(default='admin', max_length=100),
        ),
    ]
