# Generated by Django 3.0.1 on 2020-01-15 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0006_remove_machineconfiguration_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateTaskProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
                ('select_action', models.CharField(default='Default', max_length=100)),
                ('process_inbox', models.CharField(default='No', max_length=100)),
                ('process_spam', models.CharField(default='No', max_length=100)),
                ('compose_mail', models.CharField(default='No', max_length=100)),
                ('archive_or_delete', models.CharField(default='None', max_length=100)),
                ('bulk_notspam', models.CharField(default='No', max_length=100)),
                ('add_safe_sender', models.CharField(default='No', max_length=100)),
                ('color_category', models.CharField(default='No', max_length=100)),
                ('mark_flag', models.CharField(default='No', max_length=100)),
                ('click_link', models.CharField(default='No', max_length=100)),
                ('forward_mail', models.CharField(default='No', max_length=100)),
                ('report_notspam', models.CharField(default='No', max_length=100)),
                ('inbox_process_count', models.CharField(default='0', max_length=100)),
                ('notspam_count', models.CharField(default='0', max_length=100)),
                ('delete_count', models.CharField(default='0', max_length=100)),
                ('flag_count', models.CharField(default='0', max_length=100)),
                ('forward_count', models.CharField(default='0', max_length=100)),
                ('cc_count', models.CharField(default='0', max_length=100)),
                ('ss_count', models.CharField(default='0', max_length=100)),
                ('contact_count', models.CharField(default='0', max_length=100)),
                ('subject', models.CharField(default='None', max_length=100)),
                ('from_name', models.CharField(default='None', max_length=100)),
            ],
        ),
    ]
