# Generated by Django 3.0.1 on 2020-01-21 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0007_createtaskprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createtaskprofile',
            name='add_safe_sender',
            field=models.CharField(default='A_S_No', max_length=100),
        ),
        migrations.AlterField(
            model_name='createtaskprofile',
            name='bulk_notspam',
            field=models.CharField(default='B_N_S_No', max_length=100),
        ),
        migrations.AlterField(
            model_name='createtaskprofile',
            name='click_link',
            field=models.CharField(default='C_L_Yes', max_length=100),
        ),
        migrations.AlterField(
            model_name='createtaskprofile',
            name='color_category',
            field=models.CharField(default='C_C_No', max_length=100),
        ),
        migrations.AlterField(
            model_name='createtaskprofile',
            name='compose_mail',
            field=models.CharField(default='C_M_No', max_length=100),
        ),
        migrations.AlterField(
            model_name='createtaskprofile',
            name='forward_mail',
            field=models.CharField(default='F_M_No', max_length=100),
        ),
        migrations.AlterField(
            model_name='createtaskprofile',
            name='from_name',
            field=models.CharField(default='NA', max_length=100),
        ),
        migrations.AlterField(
            model_name='createtaskprofile',
            name='inbox_process_count',
            field=models.CharField(default='25', max_length=100),
        ),
        migrations.AlterField(
            model_name='createtaskprofile',
            name='mark_flag',
            field=models.CharField(default='M_F_No', max_length=100),
        ),
        migrations.AlterField(
            model_name='createtaskprofile',
            name='notspam_count',
            field=models.CharField(default='25', max_length=100),
        ),
        migrations.AlterField(
            model_name='createtaskprofile',
            name='process_inbox',
            field=models.CharField(default='P_I_Yes', max_length=100),
        ),
        migrations.AlterField(
            model_name='createtaskprofile',
            name='process_spam',
            field=models.CharField(default='P_S_Yes', max_length=100),
        ),
        migrations.AlterField(
            model_name='createtaskprofile',
            name='report_notspam',
            field=models.CharField(default='R_N_S_No', max_length=100),
        ),
        migrations.AlterField(
            model_name='createtaskprofile',
            name='subject',
            field=models.CharField(default='NA', max_length=100),
        ),
    ]
