# Generated by Django 3.0.1 on 2020-01-21 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0008_auto_20200121_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createtaskprofile',
            name='select_action',
            field=models.CharField(default='S_A_Default', max_length=100),
        ),
    ]
