# Generated by Django 3.0.1 on 2020-01-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0010_auto_20200122_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='machineconfiguration',
            name='disk_space',
            field=models.CharField(default='Not Active', max_length=10),
        ),
    ]
