# Generated by Django 3.0.1 on 2020-01-31 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0011_machineconfiguration_disk_space'),
    ]

    operations = [
        migrations.RenameField(
            model_name='machineconfiguration',
            old_name='disk_space',
            new_name='disk_usage',
        ),
    ]
