# Generated by Django 3.0.1 on 2020-02-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0013_auto_20200212_1701'),
    ]

    operations = [
        migrations.AddField(
            model_name='userseed',
            name='endtime',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='userseed',
            name='starttime',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
