# Generated by Django 3.0.1 on 2020-02-12 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0014_auto_20200212_1851'),
    ]

    operations = [
        migrations.AddField(
            model_name='userseed',
            name='seedstatus',
            field=models.CharField(default='Not In Process', max_length=100),
        ),
    ]
