# Generated by Django 3.0.1 on 2020-02-27 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0015_userseed_seedstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userseed',
            name='tasklog',
            field=models.CharField(default='Seed Insert Log - 2020-02-27 22:09:45.642363', max_length=100),
        ),
    ]
