# Generated by Django 3.0.1 on 2020-02-27 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0016_auto_20200227_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userseed',
            name='tasklog',
            field=models.CharField(default='Seed Task Log - 2020-02-27 22:14:45.909695', max_length=100),
        ),
    ]
