# Generated by Django 3.0.1 on 2020-02-27 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0017_auto_20200227_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userseed',
            name='tasklog',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
